<?php

namespace IMI\SVGProductImages;

use Magento\Framework\Image\Adapter\ImageMagick;

class SVGImageMagickAdapter extends ImageMagick
{
	/**
	 * Add basic SVG validation
	 *
	 * @param string $filePath
	 *
	 * @return bool
	 */
	public function validateUploadFile( $filePath ) {
		if (mime_content_type($filePath) == 'image/svg+xml') {
			return true;
		}
		return parent::validateUploadFile( $filePath ); // TODO: Change the autogenerated stub
	}

}